(cl:defpackage husky_gazebo_plugins-srv
  (:use )
  (:export
   "GETHUSKYJOINTSTATES"
   "<GETHUSKYJOINTSTATES-REQUEST>"
   "GETHUSKYJOINTSTATES-REQUEST"
   "<GETHUSKYJOINTSTATES-RESPONSE>"
   "GETHUSKYJOINTSTATES-RESPONSE"
   "GETHUSKYODOMETRY"
   "<GETHUSKYODOMETRY-REQUEST>"
   "GETHUSKYODOMETRY-REQUEST"
   "<GETHUSKYODOMETRY-RESPONSE>"
   "GETHUSKYODOMETRY-RESPONSE"
   "SETHUSKYCMDVEL"
   "<SETHUSKYCMDVEL-REQUEST>"
   "SETHUSKYCMDVEL-REQUEST"
   "<SETHUSKYCMDVEL-RESPONSE>"
   "SETHUSKYCMDVEL-RESPONSE"
   "SETHUSKYWHEELSPEEDS"
   "<SETHUSKYWHEELSPEEDS-REQUEST>"
   "SETHUSKYWHEELSPEEDS-REQUEST"
   "<SETHUSKYWHEELSPEEDS-RESPONSE>"
   "SETHUSKYWHEELSPEEDS-RESPONSE"
  ))

