// Generated by gencpp from file husky_gazebo_plugins/GetHuskyJointStates.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATES_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATES_H

#include <ros/service_traits.h>


#include <husky_gazebo_plugins/GetHuskyJointStatesRequest.h>
#include <husky_gazebo_plugins/GetHuskyJointStatesResponse.h>


namespace husky_gazebo_plugins
{

struct GetHuskyJointStates
{

typedef GetHuskyJointStatesRequest Request;
typedef GetHuskyJointStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHuskyJointStates
} // namespace husky_gazebo_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStates > {
  static const char* value()
  {
    return "f69960c563cc6eff60e989900150b704";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStates&) { return value(); }
};

template<>
struct DataType< ::husky_gazebo_plugins::GetHuskyJointStates > {
  static const char* value()
  {
    return "husky_gazebo_plugins/GetHuskyJointStates";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStates&) { return value(); }
};


// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStatesRequest> should match
// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStates >
template<>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStates >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyJointStatesRequest> should match
// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyJointStates >
template<>
struct DataType< ::husky_gazebo_plugins::GetHuskyJointStatesRequest>
{
  static const char* value()
  {
    return DataType< ::husky_gazebo_plugins::GetHuskyJointStates >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStatesResponse> should match
// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStates >
template<>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStates >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyJointStatesResponse> should match
// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyJointStates >
template<>
struct DataType< ::husky_gazebo_plugins::GetHuskyJointStatesResponse>
{
  static const char* value()
  {
    return DataType< ::husky_gazebo_plugins::GetHuskyJointStates >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATES_H
