// Generated by gencpp from file husky_gazebo_plugins/GetHuskyOdometry.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYODOMETRY_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYODOMETRY_H

#include <ros/service_traits.h>


#include <husky_gazebo_plugins/GetHuskyOdometryRequest.h>
#include <husky_gazebo_plugins/GetHuskyOdometryResponse.h>


namespace husky_gazebo_plugins
{

struct GetHuskyOdometry
{

typedef GetHuskyOdometryRequest Request;
typedef GetHuskyOdometryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHuskyOdometry
} // namespace husky_gazebo_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometry > {
  static const char* value()
  {
    return "34929f1f9b719059cb41724dedcf33c1";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyOdometry&) { return value(); }
};

template<>
struct DataType< ::husky_gazebo_plugins::GetHuskyOdometry > {
  static const char* value()
  {
    return "husky_gazebo_plugins/GetHuskyOdometry";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyOdometry&) { return value(); }
};


// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometryRequest> should match
// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometry >
template<>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometry >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyOdometryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyOdometryRequest> should match
// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyOdometry >
template<>
struct DataType< ::husky_gazebo_plugins::GetHuskyOdometryRequest>
{
  static const char* value()
  {
    return DataType< ::husky_gazebo_plugins::GetHuskyOdometry >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyOdometryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometryResponse> should match
// service_traits::MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometry >
template<>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_gazebo_plugins::GetHuskyOdometry >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyOdometryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyOdometryResponse> should match
// service_traits::DataType< ::husky_gazebo_plugins::GetHuskyOdometry >
template<>
struct DataType< ::husky_gazebo_plugins::GetHuskyOdometryResponse>
{
  static const char* value()
  {
    return DataType< ::husky_gazebo_plugins::GetHuskyOdometry >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::GetHuskyOdometryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYODOMETRY_H
