// Generated by gencpp from file husky_gazebo_plugins/SetHuskyWheelSpeedsRequest.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYWHEELSPEEDSREQUEST_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYWHEELSPEEDSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <husky_gazebo_plugins/WheelSpeeds.h>

namespace husky_gazebo_plugins
{
template <class ContainerAllocator>
struct SetHuskyWheelSpeedsRequest_
{
  typedef SetHuskyWheelSpeedsRequest_<ContainerAllocator> Type;

  SetHuskyWheelSpeedsRequest_()
    : wheel_speeds()  {
    }
  SetHuskyWheelSpeedsRequest_(const ContainerAllocator& _alloc)
    : wheel_speeds(_alloc)  {
  (void)_alloc;
    }



   typedef  ::husky_gazebo_plugins::WheelSpeeds_<ContainerAllocator>  _wheel_speeds_type;
  _wheel_speeds_type wheel_speeds;





  typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHuskyWheelSpeedsRequest_

typedef ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<std::allocator<void> > SetHuskyWheelSpeedsRequest;

typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest > SetHuskyWheelSpeedsRequestPtr;
typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest const> SetHuskyWheelSpeedsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.wheel_speeds == rhs.wheel_speeds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea93786adaebbf7a0cdc458efcc81166";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea93786adaebbf7aULL;
  static const uint64_t static_value2 = 0x0cdc458efcc81166ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_gazebo_plugins/SetHuskyWheelSpeedsRequest";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_gazebo_plugins/WheelSpeeds wheel_speeds\n"
"\n"
"================================================================================\n"
"MSG: husky_gazebo_plugins/WheelSpeeds\n"
"float64 back_left_wheel # back left wheel speed in m/s\n"
"float64 back_right_wheel # back right wheel speed in m/s\n"
"float64 front_left_wheel # front left wheel speed in m/s\n"
"float64 front_right_wheel # front right wheel speed in m/s\n"
;
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wheel_speeds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHuskyWheelSpeedsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsRequest_<ContainerAllocator>& v)
  {
    s << indent << "wheel_speeds: ";
    s << std::endl;
    Printer< ::husky_gazebo_plugins::WheelSpeeds_<ContainerAllocator> >::stream(s, indent + "  ", v.wheel_speeds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYWHEELSPEEDSREQUEST_H
