// Generated by gencpp from file husky_gazebo_plugins/GetHuskyJointStatesResponse.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATESRESPONSE_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace husky_gazebo_plugins
{
template <class ContainerAllocator>
struct GetHuskyJointStatesResponse_
{
  typedef GetHuskyJointStatesResponse_<ContainerAllocator> Type;

  GetHuskyJointStatesResponse_()
    : joint_states()
    , success(false)
    , status_message()  {
    }
  GetHuskyJointStatesResponse_(const ContainerAllocator& _alloc)
    : joint_states(_alloc)
    , success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _joint_states_type;
  _joint_states_type joint_states;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHuskyJointStatesResponse_

typedef ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<std::allocator<void> > GetHuskyJointStatesResponse;

typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesResponse > GetHuskyJointStatesResponsePtr;
typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesResponse const> GetHuskyJointStatesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint_states == rhs.joint_states &&
    lhs.success == rhs.success &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f69960c563cc6eff60e989900150b704";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf69960c563cc6effULL;
  static const uint64_t static_value2 = 0x60e989900150b704ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_gazebo_plugins/GetHuskyJointStatesResponse";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/JointState joint_states\n"
"bool success                         # return true if get successful\n"
"string status_message                # comments if available\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_states);
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHuskyJointStatesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_gazebo_plugins::GetHuskyJointStatesResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_states: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.joint_states);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATESRESPONSE_H
