// Generated by gencpp from file husky_gazebo_plugins/GetHuskyJointStatesRequest.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATESREQUEST_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_gazebo_plugins
{
template <class ContainerAllocator>
struct GetHuskyJointStatesRequest_
{
  typedef GetHuskyJointStatesRequest_<ContainerAllocator> Type;

  GetHuskyJointStatesRequest_()
    {
    }
  GetHuskyJointStatesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetHuskyJointStatesRequest_

typedef ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<std::allocator<void> > GetHuskyJointStatesRequest;

typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesRequest > GetHuskyJointStatesRequestPtr;
typedef boost::shared_ptr< ::husky_gazebo_plugins::GetHuskyJointStatesRequest const> GetHuskyJointStatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace husky_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_gazebo_plugins/GetHuskyJointStatesRequest";
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHuskyJointStatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::husky_gazebo_plugins::GetHuskyJointStatesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_GETHUSKYJOINTSTATESREQUEST_H
