// Generated by gencpp from file husky_gazebo_plugins/SetHuskyWheelSpeedsResponse.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYWHEELSPEEDSRESPONSE_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYWHEELSPEEDSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_gazebo_plugins
{
template <class ContainerAllocator>
struct SetHuskyWheelSpeedsResponse_
{
  typedef SetHuskyWheelSpeedsResponse_<ContainerAllocator> Type;

  SetHuskyWheelSpeedsResponse_()
    : success(false)
    , status_message()  {
    }
  SetHuskyWheelSpeedsResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetHuskyWheelSpeedsResponse_

typedef ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<std::allocator<void> > SetHuskyWheelSpeedsResponse;

typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse > SetHuskyWheelSpeedsResponsePtr;
typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse const> SetHuskyWheelSpeedsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ec6f3eff0161f42ULL;
  static const uint64_t static_value2 = 0x57b808b12bc830c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_gazebo_plugins/SetHuskyWheelSpeedsResponse";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success                         # return true if set successful\n"
"string status_message                # comments if available\n"
"\n"
;
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHuskyWheelSpeedsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_gazebo_plugins::SetHuskyWheelSpeedsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYWHEELSPEEDSRESPONSE_H
