// Generated by gencpp from file husky_gazebo_plugins/SetHuskyCmdVelRequest.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYCMDVELREQUEST_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYCMDVELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace husky_gazebo_plugins
{
template <class ContainerAllocator>
struct SetHuskyCmdVelRequest_
{
  typedef SetHuskyCmdVelRequest_<ContainerAllocator> Type;

  SetHuskyCmdVelRequest_()
    : cmd_vel()  {
    }
  SetHuskyCmdVelRequest_(const ContainerAllocator& _alloc)
    : cmd_vel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _cmd_vel_type;
  _cmd_vel_type cmd_vel;





  typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHuskyCmdVelRequest_

typedef ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<std::allocator<void> > SetHuskyCmdVelRequest;

typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyCmdVelRequest > SetHuskyCmdVelRequestPtr;
typedef boost::shared_ptr< ::husky_gazebo_plugins::SetHuskyCmdVelRequest const> SetHuskyCmdVelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd_vel == rhs.cmd_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator1> & lhs, const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "923d2c355ddd6c74246b896ebe62199f";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x923d2c355ddd6c74ULL;
  static const uint64_t static_value2 = 0x246b896ebe62199fULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_gazebo_plugins/SetHuskyCmdVelRequest";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist cmd_vel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHuskyCmdVelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_gazebo_plugins::SetHuskyCmdVelRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYCMDVELREQUEST_H
