// Generated by gencpp from file husky_gazebo_plugins/SetHuskyCmdVel.msg
// DO NOT EDIT!


#ifndef HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYCMDVEL_H
#define HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYCMDVEL_H

#include <ros/service_traits.h>


#include <husky_gazebo_plugins/SetHuskyCmdVelRequest.h>
#include <husky_gazebo_plugins/SetHuskyCmdVelResponse.h>


namespace husky_gazebo_plugins
{

struct SetHuskyCmdVel
{

typedef SetHuskyCmdVelRequest Request;
typedef SetHuskyCmdVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHuskyCmdVel
} // namespace husky_gazebo_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVel > {
  static const char* value()
  {
    return "cf6e6c41c08fa53df96254507e254422";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVel&) { return value(); }
};

template<>
struct DataType< ::husky_gazebo_plugins::SetHuskyCmdVel > {
  static const char* value()
  {
    return "husky_gazebo_plugins/SetHuskyCmdVel";
  }

  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVel&) { return value(); }
};


// service_traits::MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVelRequest> should match
// service_traits::MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVel >
template<>
struct MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVel >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_gazebo_plugins::SetHuskyCmdVelRequest> should match
// service_traits::DataType< ::husky_gazebo_plugins::SetHuskyCmdVel >
template<>
struct DataType< ::husky_gazebo_plugins::SetHuskyCmdVelRequest>
{
  static const char* value()
  {
    return DataType< ::husky_gazebo_plugins::SetHuskyCmdVel >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVelResponse> should match
// service_traits::MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVel >
template<>
struct MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_gazebo_plugins::SetHuskyCmdVel >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_gazebo_plugins::SetHuskyCmdVelResponse> should match
// service_traits::DataType< ::husky_gazebo_plugins::SetHuskyCmdVel >
template<>
struct DataType< ::husky_gazebo_plugins::SetHuskyCmdVelResponse>
{
  static const char* value()
  {
    return DataType< ::husky_gazebo_plugins::SetHuskyCmdVel >::value();
  }
  static const char* value(const ::husky_gazebo_plugins::SetHuskyCmdVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_GAZEBO_PLUGINS_MESSAGE_SETHUSKYCMDVEL_H
